name: Rust Cross-Compile

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    strategy:
      matrix:
        target:
          - { target: x86_64-pc-windows-gnu, runs-on: windows-latest }
          - { target: aarch64-apple-darwin, runs-on: macos-latest }
    runs-on: ${{ matrix.target.runs-on }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install target
        run: rustup target add ${{ matrix.target.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.target.target }}-binary
          path: target/${{ matrix.target.target }}/release/